export { LogicalSearchDriver } from './driver.js'
export type { SearchDriver, SearchHit } from './driver.js'
export { enqueueOutbox, processOutboxAsync } from './outbox.js'
export type { OutboxEntry } from './outbox.js'
export { buildSearchDoc } from './doc-builder.js'
