// setup:e2e — bring up the ISOLATED e2e middleware and seed it.
// Order matters: compose -> pg ready -> migrate -> fga bootstrap (writes store/
// model ids to .env.e2e.local) -> fga seed -> db seed. FGA seed needs the store/
// model from bootstrap; db seed needs migrated tables.
import { execSync } from "node:child_process";
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repo = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const run = (cmd, opts = {}) => execSync(cmd, { cwd: repo, stdio: "inherit", ...opts });
const capture = (cmd) => execSync(cmd, { cwd: repo, encoding: "utf8" });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const LOCAL = join(repo, ".env.e2e.local");
const ENVS = "--env-file=.env.e2e --env-file=.env.e2e.local";

// ok=true: require a 2xx. ok=false: any HTTP response counts (e.g. SeaweedFS S3
// returns 403 when up but unauthenticated).
async function waitFor(url, name, { ok = true, tries = 60 } = {}) {
  for (let i = 0; i < tries; i++) {
    try {
      const r = await fetch(url);
      if (ok ? r.ok : true) return;
    } catch {
      /* not up yet */
    }
    await sleep(1000);
  }
  throw new Error(`${name} not ready after ${tries}s (${url})`);
}

// .env.e2e.local must exist before any --env-file=.env.e2e.local command.
if (!existsSync(LOCAL)) writeFileSync(LOCAL, "# generated by setup:e2e\n");

console.log("[e2e] docker compose up (project wikistead-e2e)…");
run("docker compose -f docker-compose.e2e.yml up -d --wait");

console.log("[e2e] waiting for openfga + meilisearch + storage…");
await waitFor("http://localhost:8090/healthz", "openfga");
await waitFor("http://localhost:7701/health", "meilisearch");
// SeaweedFS S3 returns 403 (unauthenticated) when up — any HTTP response is ready.
await waitFor("http://localhost:9002", "storage-s3", { ok: false });

console.log("[e2e] migrate…");
run(`npx tsx --env-file=.env.e2e apps/server/src/migrate.ts`);

console.log("[e2e] fga bootstrap…");
const out = capture(`npx tsx --env-file=.env.e2e infra/openfga/bootstrap.ts`);
const storeId = /OPENFGA_STORE_ID=(.+)/.exec(out)?.[1]?.trim();
const modelId = /OPENFGA_MODEL_ID=(.+)/.exec(out)?.[1]?.trim();
if (!storeId || !modelId) throw new Error(`bootstrap did not emit store/model ids:\n${out}`);
writeFileSync(LOCAL, `# generated by setup:e2e — do not commit\nOPENFGA_STORE_ID=${storeId}\nOPENFGA_MODEL_ID=${modelId}\n`);
console.log(`[e2e] wrote .env.e2e.local (store ${storeId})`);

console.log("[e2e] fga seed…");
run(`npx tsx ${ENVS} infra/openfga/seed.ts`);

console.log("[e2e] db seed…");
run(`npx tsx --env-file=.env.e2e infra/db/seed.ts`);

console.log("[e2e] setup complete. Run: pnpm test:e2e");
