// #484 slice 2 (pin gap #2): "the pin needs a test that two offsets don't collide." The three
// worktrees (a/b/c) run their suites against per-session isolated stacks selected by WKS_STACK_OFFSET.
// Isolation is only real if no two offsets — and no test stack vs the dev stack — ever share a host
// port. This is a PURE test of the port derivation (no containers), so it fails the moment a base or
// stride change reintroduces an overlap, before anyone debugs a phantom flake.
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
// repo-root script (same module server-test-up.mjs / the e2e scripts consume) — a plain .mjs with no
// types, so import it untyped rather than adding a .d.ts for a test-only infra helper.
// @ts-expect-error — untyped JS helper
import { serverTestPorts, e2ePorts, DEV_PORTS, staleStackEnvPorts } from '../../../../scripts/stack-offset.mjs'

const OFFSETS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
// only the host-port fields (drop offset/project and any string fields)
const portsOf = (m: Record<string, unknown>): number[] =>
  Object.entries(m)
    .filter(([k, v]) => k !== 'offset' && typeof v === 'number')
    .map(([, v]) => v as number)

describe('#484 stack isolation — port maps never collide', () => {
  it('e2e offset 0 reproduces the shipped literals (byte-for-byte default)', () => {
    expect(e2ePorts(0)).toMatchObject({
      project: 'wikistead-e2e',
      pg: 5433, valkey: 6380, fgaHttp: 8090, fgaGrpc: 8091, meili: 7701, s3: 9002, smtp: 1026, mailpit: 8026,
      server: 4010, collab: 4110, web: 5180, webReal: 5181, issuer: 4444,
    })
  })

  it('server-test offset 0 reproduces the shipped literals', () => {
    expect(serverTestPorts(0)).toMatchObject({
      project: 'wikistead-server-test',
      pg: 5434, valkey: 6381, fgaHttp: 8092, fgaGrpc: 8093, meili: 7702, s3: 9003, smtp: 1027, mailpit: 8027,
    })
  })

  it('within each family, no two offsets share a port', () => {
    for (const fam of [serverTestPorts, e2ePorts]) {
      const all = OFFSETS.flatMap((o) => portsOf(fam(o)))
      expect(new Set(all).size, `${fam.name}: duplicate port across offsets`).toBe(all.length)
    }
  })

  it('an e2e stack never collides with a server-test stack (any offsets)', () => {
    for (const eo of OFFSETS) {
      const e = new Set(portsOf(e2ePorts(eo)))
      for (const so of OFFSETS) {
        const overlap = portsOf(serverTestPorts(so)).filter((p) => e.has(p))
        expect(overlap, `e2e#${eo} ∩ server-test#${so}`).toEqual([])
      }
    }
  })

  it('no test stack (any offset) lands on a dev host port', () => {
    const dev = new Set(Object.values(DEV_PORTS))
    for (const fam of [serverTestPorts, e2ePorts]) {
      for (const o of OFFSETS) {
        const overlap = portsOf(fam(o)).filter((p) => dev.has(p))
        expect(overlap, `${fam.name}#${o} ∩ dev`).toEqual([])
      }
    }
  })

  // #869: a host port is not only "is anyone listening on it". The kernel hands out numbers from
  // `ip_local_port_range` as SOURCE ports for outgoing connections, and one that has been used sits in
  // TIME-WAIT for a minute afterwards — bindable by nobody, invisible to `ss -ltn`. The isolated app
  // band first sat at 42xxx, inside that range, and the suite died at startup with "Port 42044 is
  // already in use" while nothing was listening on it: the stack's OWN outgoing connection had taken
  // the number on the way up.
  //
  // The range is READ, never assumed. Hardcoding 32768-60999 would pass on a host configured
  // differently while the suite kept dying there, which is the failure this is here to catch.
  it('no derived port falls inside the kernel ephemeral range (it could be taken as a source port)', () => {
    let raw: string
    try {
      raw = readFileSync('/proc/sys/net/ipv4/ip_local_port_range', 'utf8')
    } catch {
      return // not Linux, or a kernel that does not publish it — nothing to compare against
    }
    const [lo, hi] = raw.trim().split(/\s+/).map(Number)
    expect(Number.isInteger(lo) && Number.isInteger(hi) && lo < hi, `unreadable range: ${raw}`).toBe(true)

    const inRange = (p: number) => p >= lo && p <= hi
    for (const fam of [serverTestPorts, e2ePorts]) {
      for (const o of OFFSETS) {
        const caught = portsOf(fam(o)).filter(inRange)
        expect(caught, `${fam.name}#${o} inside ${lo}-${hi}`).toEqual([])
      }
    }
    expect((Object.values(DEV_PORTS) as number[]).filter(inRange), `dev inside ${lo}-${hi}`).toEqual([])
  })

  // #869: moving the band is not enough on its own. `.env.e2e.local` is generated by setup and loaded
  // FIRST, so a file written before the move keeps starting the stack on the old ports while the runner
  // polls the new ones — a sixty-second wait ending in a timeout that names neither side.
  describe('a local env written for the old band is named, not waited on', () => {
    const P = e2ePorts(1)
    const asFile = (m: Record<string, number>) =>
      ['OPENFGA_STORE_ID=01ABC', ...Object.entries(m).map(([k, v]) => `${k}=${v}`)].join('\n') + '\n'

    it('a file from before the move disagrees on every app port', () => {
      const old = asFile({ SERVER_PORT: 42000, COLLAB_PORT: 42002, WEB_PORT: 42004 })
      expect(staleStackEnvPorts(old, P).map((s: { key: string }) => s.key))
        .toEqual(['SERVER_PORT', 'COLLAB_PORT', 'WEB_PORT'])
    })

    it('one drifted port is still caught, and reported with both numbers', () => {
      const one = asFile({ SERVER_PORT: P.server, COLLAB_PORT: 42002, WEB_PORT: P.web })
      expect(staleStackEnvPorts(one, P)).toEqual([{ key: 'COLLAB_PORT', found: 42002, expected: P.collab }])
    })

    it('the file setup writes for THIS offset disagrees about nothing', () => {
      expect(staleStackEnvPorts(asFile({ SERVER_PORT: P.server, COLLAB_PORT: P.collab, WEB_PORT: P.web }), P))
        .toEqual([])
    })

    // A file that never names the port cannot disagree with it — silence is not a mismatch, or every
    // partial env file (and the empty string a missing file reads as) would refuse to start the suite.
    it('a file that names no app ports is not stale', () => {
      expect(staleStackEnvPorts('OPENFGA_STORE_ID=01ABC\nWEB_PORT=\n', P)).toEqual([])
      expect(staleStackEnvPorts('', P)).toEqual([])
    })
  })

  it('every isolated e2e offset gets its own compose project (separate volumes → separate FGA store)', () => {
    const names = OFFSETS.map((o) => e2ePorts(o).project)
    expect(new Set(names).size).toBe(names.length)
  })
})
