// setup:server-test — bring up the ISOLATED server integration-test middleware and seed it.
// Mirrors tests/e2e/scripts/up.mjs (the server suite runs buildApp() in-process, so unlike
// e2e there are no app processes to start — only middleware + migrate + seed).
// Order matters: compose -> pg ready -> migrate -> fga bootstrap (writes store/model ids to
// .env.server-test.local) -> fga seed -> db seed. #268.
import { execSync } from "node:child_process";
import { writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repo = join(dirname(fileURLToPath(import.meta.url)), "..");
const run = (cmd, opts = {}) => execSync(cmd, { cwd: repo, stdio: "inherit", ...opts });
const capture = (cmd) => execSync(cmd, { cwd: repo, encoding: "utf8" });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const LOCAL = join(repo, ".env.server-test.local");
const ENVS = "--env-file=.env.server-test --env-file=.env.server-test.local";

// ok=true: require a 2xx. ok=false: any HTTP response counts (SeaweedFS S3 returns 403
// when up but unauthenticated).
async function waitFor(url, name, { ok = true, tries = 60 } = {}) {
  for (let i = 0; i < tries; i++) {
    try {
      const r = await fetch(url);
      if (ok ? r.ok : true) return;
    } catch {
      /* not up yet */
    }
    await sleep(1000);
  }
  throw new Error(`${name} not ready after ${tries}s (${url})`);
}

// .env.server-test.local must exist before any --env-file=.env.server-test.local command.
if (!existsSync(LOCAL)) writeFileSync(LOCAL, "# generated by setup:server-test\n");

console.log("[server-test] docker compose up (project wikistead-server-test)…");
run("docker compose -f docker-compose.server-test.yml up -d --wait");

console.log("[server-test] waiting for openfga + meilisearch + storage…");
await waitFor("http://localhost:8092/healthz", "openfga");
await waitFor("http://localhost:7702/health", "meilisearch");
await waitFor("http://localhost:9003", "storage-s3", { ok: false });

console.log("[server-test] migrate…");
run(`npx tsx --env-file=.env.server-test apps/server/src/migrate.ts`);

console.log("[server-test] fga bootstrap…");
const out = capture(`npx tsx --env-file=.env.server-test infra/openfga/bootstrap.ts`);
const storeId = /OPENFGA_STORE_ID=(.+)/.exec(out)?.[1]?.trim();
const modelId = /OPENFGA_MODEL_ID=(.+)/.exec(out)?.[1]?.trim();
if (!storeId || !modelId) throw new Error(`bootstrap did not emit store/model ids:\n${out}`);
writeFileSync(LOCAL, `# generated by setup:server-test — do not commit\nOPENFGA_STORE_ID=${storeId}\nOPENFGA_MODEL_ID=${modelId}\n`);
console.log(`[server-test] wrote .env.server-test.local (store ${storeId})`);

console.log("[server-test] fga seed…");
run(`npx tsx ${ENVS} infra/openfga/seed.ts`);

console.log("[server-test] db seed…");
run(`npx tsx --env-file=.env.server-test infra/db/seed.ts`);

console.log("[server-test] setup complete. Run: pnpm --filter @wikistead/server test");
