// setup:server-test — bring up the ISOLATED server integration-test middleware and seed it.
// Mirrors tests/e2e/scripts/up.mjs (the server suite runs buildApp() in-process, so unlike
// e2e there are no app processes to start — only middleware + migrate + seed).
// Order matters: compose -> pg ready -> migrate -> fga bootstrap (writes store/model ids to
// .env.server-test.local) -> fga seed -> db seed. #268.
import { execSync } from "node:child_process";
import { writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { serverTestPorts, serverTestComposeEnv } from "./stack-offset.mjs";

const repo = join(dirname(fileURLToPath(import.meta.url)), "..");
// #484: the port map + compose env for THIS session's stack. Offset 0 (unset) = the original ports.
const P = serverTestPorts();
// #484 fix (split-brain at offset>=1): every child step below (migrate / fga bootstrap / seeds) used to
// load ONLY the static .env.server-test — the ORIGINAL ports — so at an offset they migrated and wrote
// the FGA model into the SHARED stack while the fga seed (which also loads .env.server-test.local, i.e.
// the offset URLs) ran against THIS stack with a model id that lives elsewhere → 400 invalid model, and
// the offset postgres was never migrated at all. Offset 0 made both coincide, which is what hid it.
// Real environment variables always beat --env-file (Node never lets an env file override an already-set
// var), so injecting the offset connection URLs here re-points every step at THIS stack regardless of
// which env files the command names.
const stackEnv = {
  DATABASE_URL: `postgres://app:app@localhost:${P.pg}/app`,
  DATABASE_ADMIN_URL: `postgres://postgres:postgres@localhost:${P.pg}/app`,
  VALKEY_URL: `redis://localhost:${P.valkey}`,
  OPENFGA_API_URL: `http://localhost:${P.fgaHttp}`,
  MEILI_HOST: `http://localhost:${P.meili}`,
  S3_ENDPOINT: `http://localhost:${P.s3}`,
  SMTP_PORT: String(P.smtp),
  MAILPIT_API_URL: `http://localhost:${P.mailpit}/api/v1`,
};
const composeEnv = { ...process.env, ...serverTestComposeEnv(P), ...stackEnv };
const run = (cmd, opts = {}) => execSync(cmd, { cwd: repo, stdio: "inherit", env: composeEnv, ...opts });
const capture = (cmd) => execSync(cmd, { cwd: repo, encoding: "utf8", env: composeEnv });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const LOCAL = join(repo, ".env.server-test.local");
const ENVS = "--env-file=.env.server-test --env-file=.env.server-test.local";

// ok=true: require a 2xx. ok=false: any HTTP response counts (SeaweedFS S3 returns 403
// when up but unauthenticated).
async function waitFor(url, name, { ok = true, tries = 60 } = {}) {
  for (let i = 0; i < tries; i++) {
    try {
      const r = await fetch(url);
      if (ok ? r.ok : true) return;
    } catch {
      /* not up yet */
    }
    await sleep(1000);
  }
  throw new Error(`${name} not ready after ${tries}s (${url})`);
}

// .env.server-test.local must exist before any --env-file=.env.server-test.local command.
if (!existsSync(LOCAL)) writeFileSync(LOCAL, "# generated by setup:server-test\n");

console.log(`[server-test] docker compose up (project ${P.project}, offset ${P.offset})…`);
run("docker compose -f docker-compose.server-test.yml up -d --wait");

console.log("[server-test] waiting for openfga + meilisearch + storage…");
await waitFor(`http://localhost:${P.fgaHttp}/healthz`, "openfga");
await waitFor(`http://localhost:${P.meili}/health`, "meilisearch");
await waitFor(`http://localhost:${P.s3}`, "storage-s3", { ok: false });

console.log("[server-test] migrate…");
run(`npx tsx --env-file=.env.server-test apps/server/src/migrate.ts`);

console.log("[server-test] fga bootstrap…");
const out = capture(`npx tsx --env-file=.env.server-test infra/openfga/bootstrap.ts`);
const storeId = /OPENFGA_STORE_ID=(.+)/.exec(out)?.[1]?.trim();
const modelId = /OPENFGA_MODEL_ID=(.+)/.exec(out)?.[1]?.trim();
if (!storeId || !modelId) throw new Error(`bootstrap did not emit store/model ids:\n${out}`);
// #484: .env.server-test.local loads BEFORE .env.server-test and wins (loadEnvFile never overrides an
// already-set var), so the offset-derived connection URLs here move the suite onto this session's
// stack. At offset 0 these equal the static .env.server-test values — a harmless restatement.
writeFileSync(LOCAL, [
  `# generated by setup:server-test — do not commit (stack offset ${P.offset})`,
  `OPENFGA_STORE_ID=${storeId}`,
  `OPENFGA_MODEL_ID=${modelId}`,
  `DATABASE_URL=postgres://app:app@localhost:${P.pg}/app`,
  `DATABASE_ADMIN_URL=postgres://postgres:postgres@localhost:${P.pg}/app`,
  `VALKEY_URL=redis://localhost:${P.valkey}`,
  `OPENFGA_API_URL=http://localhost:${P.fgaHttp}`,
  `MEILI_HOST=http://localhost:${P.meili}`,
  `S3_ENDPOINT=http://localhost:${P.s3}`,
  `SMTP_PORT=${P.smtp}`,
  `MAILPIT_API_URL=http://localhost:${P.mailpit}/api/v1`,
  ``,
].join("\n"));
console.log(`[server-test] wrote .env.server-test.local (store ${storeId}, pg ${P.pg}, fga ${P.fgaHttp})`);

console.log("[server-test] fga seed…");
run(`npx tsx ${ENVS} infra/openfga/seed.ts`);

console.log("[server-test] db seed…");
run(`npx tsx --env-file=.env.server-test infra/db/seed.ts`);

console.log("[server-test] setup complete. Run: pnpm --filter @wikistead/server test");
